version: '3.8'

services:
  ui:
    container_name: ui
    image: devopseasylearning/tarzan-ui:v0.0.1
    environment:
      - AUTH_HOST=auth
      - AUTH_PORT=8080
      - WEATHER_HOST=weather
      - WEATHER_PORT=5000
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
    ports:
      - "3000:3000"
    networks:
      - tarzan

  auth:
    container_name: auth
    image: devopseasylearning/tarzan-auth:v0.0.1
    environment:
      - DB_HOST=db
      - DB_PASSWORD=my-secret-pw
    ports:
      - "3306:3306"
    networks:
      - tarzan

  db:
    container_name: db
    image: mysql:8.0.2
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data to named volume
    # ports:
    #   - "3306:3306"
    networks:
      - tarzan

  weather:
    container_name: weather
    image: devopseasylearning/tarzan-weather:v0.0.2
    environment:
      - APIKEY=ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
    networks:
      - tarzan

  redis:
    container_name: redis
    image: redis
    environment:
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
    volumes:
      - redis_data:/data        # Persist Redis data to named volume
    ports:
      - "6379:6379"
    networks:
      - tarzan

networks:
  tarzan:
    driver: bridge

volumes:
  db_data:    # Define named volume for MySQL data persistence
  redis_data: # Define named volume for Redis data persistence
